version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: TORCphysics/docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: TORCphysics/docs/conf.py
